name: Update Database

on:
  schedule:
    - cron: '0 18 * * *'
    # - cron: '*/2 * * * *'

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      # Клонуємо репозиторій
      - name: Checkout repository
        uses: actions/checkout@v3

      # Викликаємо API вашого Next.js проекту
      - name: Call Next.js API
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
          STAKING_SECRET_KEY: ${{ secrets.STAKING_SECRET_KEY }}
        run: |
          curl -v --max-time 10 -L -X POST https://${VERCEL_URL}/api/updateStaking \
          -H "Content-Type: application/json" \
          -H "x-secret-key: ${STAKING_SECRET_KEY}"
